In [5]:
import numpy as np
print("numpy loaded successfully")

numpy loaded successfully


In [6]:
np.array(1)
print(type(np.array(1)))  # Output: <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [7]:
arr= np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]
print(type(arr))  # Output: <class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
print(len (arr) )  # Output: 10



5


In [10]:
## attribute
print(arr.shape)  # Output: (5,)
print(arr.ndim)  # Output: 1
print(arr.size)  # Output: 5


(5,)
1
5


In [12]:
#methods
print(np.arange(0,10))
  

[0 1 2 3 4 5 6 7 8 9]


In [13]:
np.random.rand(3, 4)

array([[0.28212808, 0.16873527, 0.30677204, 0.40455936],
       [0.07984483, 0.01049751, 0.44007163, 0.10705633],
       [0.28852512, 0.00710327, 0.11092125, 0.58941038]])

In [15]:
np.random.randint(0,10,10)

array([4, 5, 8, 5, 1, 5, 6, 3, 4, 0], dtype=int32)